services:
  dnschef:
    image: dnschef-ng:latest
    container_name: dnschef
    ports:
      - "127.0.0.1:53:53"
    expose:
      - "80"
    volumes:
      - ./dnschef.toml:/etc/dnschef.toml
    environment:
      - INTERFACE=0.0.0.0
      - NAMESERVERS=["8.8.8.8"]
      - PORT=53
      - TCP=false
      - IPV6=false
      - CONFIGFILE=/etc/dnschef.toml