[tool.poetry]
name = "dnschef"
version = "0.6"
description = "DNSChef is a highly configurable DNS Proxy for Penetration Testers and Malware Analysts"
authors = ["Marcello Salvati <byt3bl33d3r@pm.me>"]
readme = "README.md"
homepage = "https://github.com/Porchetta-Industries/dnschef"
repository = "https://github.com/Porchetta-Industries/dnschef"
exclude = ["tests"]
include = ["LICENSE"]
license = ""
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Topic :: Security",
]

packages = [
    { include = "dnschef"}
]

[tool.poetry.scripts]
dnschef = 'dnschef.__main__:main'

[tool.poetry.dependencies]
python = "^3.8.0"
dnslib = "^0.9.16"
rich = "^10.16.1"
structlog = "^21.5.0"
fastapi = { version = "^0.70.1", optional = true }
uvicorn = { version = "^0.16.0", optional = true }

[tool.poetry.extras]
api = ["fastapi", "uvicorn"]

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"
flake8 = "*"
black = "*"
icecream = "*"
uvicorn = "^0.16.0"
httpie = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
