name: Push Image to GitHub Container Registry

on:
  workflow_run:
    workflows:
      - "Python package"
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install package and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Extract version
        id: extract_version
        run: |
          echo "version=$(python -c 'from dnschef import __version__; print(__version__)')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower repository owner
        id: lower_owner
        run: echo "lower_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ steps.lower_owner.outputs.lower_owner }}/dnschef-ng:${{ steps.extract_version.outputs.version }}
            ghcr.io/${{ steps.lower_owner.outputs.lower_owner }}/dnschef-ng:latest